### ISSUE TITLE
protonvpn-gui app with openrc-elogind

### ISSUE THREAD

**Issue by lsg333** [Qeenon/mawa#11]
I am trying to install protonvpn-gui app  in Gentoo with openrc but i can't since dbus is configured to work with systemd only i'm here to kindly ask if it would be possible to add the elogind option there to make it work with openrc.
Thanks a lot for your work!

**Comment by Miezhiko** [comment]
@lsg333 honestly I think it's more question to upstream, 

their repository is there: https://github.com/ProtonVPN/linux-app
