### ISSUE TITLE
overlaying dev-ml/dose3 might become unnecessary

### ISSUE THREAD

**Issue by fogti** [Qeenon/mawa#21]
Hi, I'm currently trying to upstream a fix for dose3, after that gets upstreamed, it won't be necessary to patch it anymore. (https://github.com/gentoo/gentoo/pull/37544)

**Comment by Miezhiko** [comment]
@fogti I'd keep it here, I have zero control over what is happening on `::gentoo` so I need to have ability to fix bugs and update faster than it gets there. Treat it as my personal suggestion but you better join Gentoo development team to be able to do big updates, Gentoo will continue removing ebuilds without active maintainers in teams https://blogs.gentoo.org/mgorny/2024/05/30/the-dead-weight-of-packages-in-gentoo alternatively get all involved people together and create area-specific overlay (exherbo way)

**Comment by fogti** [comment]
I also want to inform you that:
```shell
src_compile() {
	dune-compile "$PN"
}
```
is the minimal patch to make dose3 not depend on archivers. So the patch for dose3-extra is unnecessary.
I feel like it would make sense to have something like the `haskell` overlay for bleeding-edge OCaml stuff. If anyone else would also have interest in that, I'm willing to join forces and help with maintenance.

**Comment by Miezhiko** [comment]
good catch,
actually for now pull requests are very welcome, at least simpler for me to review and test.

or if your ::gentoo request will be merged it's fine, I eventually drop updated upstream things
