### ISSUE TITLE
Drawing meson sed

### ISSUE THREAD

**Issue by joostruis** [Qeenon/mawa#9]
Heya. By accident bumped into this issue.

https://github.com/maoschanz/drawing/issues/509

I have no idea why you needed the sed command in src_prepare() but I think that fails against current master.

**Comment by Miezhiko** [comment]
thank you for reporting, this is live ebuild so it's expected that it may fail

I had workaround over some problem there <https://github.com/Miezhiko/Overlay/blob/mawa/media-gfx/drawing/drawing-9999.ebuild#L44>

but seems like problem was fixed and that line could be safely dropped, will do slightly later.
